mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('town.urls')),
)

town/urls.py
from django.conf.urls import patterns, include, url
from .import views


urlpatterns = patterns('',
    url(r'^$', views.town_list),
    url(r'^town/(?P<pk>[0-9]+)/$', views.town_detail),
    url(r'^shop/(?P<pk>[0-9]+)/$', views.shop_detail),
    url(r'^item/(?P<pk>[0-9]+)/$', views.item_detail),
    url(r'^cart/$', views.cart_list),
    url(r'^cart/add/$', views.cart_add),
    url(r'^cart/delete/$', views.cart_delete),

)

town/models.py
from django.db import models
from django.utils import timezone


class Town(models.Model):
    name = models.CharField(max_length=200, verbose_name="Town")
    size = models.IntegerField()
    address = models.CharField(
        max_length=200, null=True, blank=True, verbose_name="住所")
    created = models.DateTimeField(default=timezone.now)
    modified = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Shop(models.Model):
    owner = models.ForeignKey('auth.User', verbose_name="所有者")
    area = models.ForeignKey('Town', verbose_name="所属の町")
    name = models.CharField(max_length=255, verbose_name="Shop")
    description = models.TextField(null=True, blank=True, verbose_name="商品説明")
    size = models.IntegerField()
    address = models.CharField(
        max_length=255, null=True, blank=True, verbose_name="住所")
    created = models.DateTimeField(default=timezone.now)
    modified = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=255, verbose_name="商品名")
    price = models.IntegerField(default=0)
    description = models.TextField(null=True, blank=True, verbose_name="商品説明")
    created = models.DateTimeField(default=timezone.now)
    modified = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Stock(models.Model):
    shop = models.ForeignKey('Shop')
    item = models.OneToOneField('Item')
    quantity = models.IntegerField(default=0)
    created = models.DateTimeField(default=timezone.now)
    modified = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{} * {}".format(self.item.name, self.quantity)


class Order(models.Model):
    customer = models.ForeignKey('auth.User')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Ordered at {}".format(
            self.created.strftime("%Y-%m-%d %H:%m:%s"))


class OrderItem(models.Model):
    order = models.ForeignKey('Order')
    item = models.ForeignKey('Item')
    quantity = models.IntegerField()

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.item.name


class OrderStatus(models.Model):
    DEAL_STATUS = 1
    STATUS_CHOICES = (
        (DEAL_STATUS, '契約'),
    )

    order = models.OneToOneField('Order')
    status = models.IntegerField(choices=STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


class Cart(models.Model):
    customer = models.OneToOneField('auth.User')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "購入者: {}".format(self.customer.username)


class CartItem(models.Model):
    cart = models.ForeignKey('Cart')
    item = models.ForeignKey('Item')
    quantity = models.IntegerField()

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.item.name

town/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.contrib import messages
from .models import Town, Shop, Item, Cart, CartItem


def town_list(request):
    towns = Town.objects.all()
    return render(request, 'town/town_list.html', {'towns': towns})


def town_detail(request, pk):
    town = Town.objects.get(pk=pk)
    shops = Shop.objects.filter(area=town)
    params = {
        'town': town,
        'shops': shops,
    }
    return render(request, 'town/town_detail.html', params)


def shop_detail(request, pk):
    shop = Shop.objects.get(pk=pk)

    params = {
        'shop': shop
    }
    return render(request, 'shop/shop_detail.html', params)


def item_detail(request, pk):
    item = Item.objects.get(pk=pk)
    params = {
        'item': item
    }
    return render(request, 'item/item_detail.html', params)


def cart_list(request):
    cart = Cart.objects.get(customer=request.user)
    params = {
        'cart': cart
    }
    return render(request, 'cart/cart_list.html', params)


def cart_add(request):
    if request.method == 'POST':
        # cart がないなら作成
        cart, cart_created = Cart.objects.get_or_create(
            customer=request.user)
        item_id = request.POST.get("item_id", 0)
        item = Item.objects.get(pk=item_id)
        quantity = 1
        cart_item = None
        try:
            # すでに同じ商品がある場合
            cart_item = CartItem.objects.get(cart=cart, item=item)
            cart_item.quantity += quantity
        except CartItem.DoesNotExist:
            # 新規商品
            cart_item = CartItem(cart=cart, item=item, quantity=quantity)
        # save
        cart_item.save()
        messages.success(request, 'カートに商品が追加されました。')
        return redirect('town.views.item_detail', pk=item_id)
    else:
        raise Http404


def cart_delete(request):
    if request.method == 'POST':
        item_id = request.POST.get("item_id", 0)
        # 一件しか取得されない
        cart_items = Cart.objects.get(
            customer=request.user).cartitem_set.filter(item_id=item_id)
        item_name = cart_items[0].item.name
        # 削除
        cart_items.delete()
        messages.success(request, '{}が削除されました。'.format(item_name))
        return redirect('town.views.cart_list')

town/templates/cart/cart_list.html
{% extends 'town/base.html' %}
{% load humanize %}
{% block content %}
    <h2>お買い物かご</h2>
    {% with cart_items=cart.cartitem_set.all %}
    <ul>
    {% for cart_item in cart_items %}
        <li style="margin-bottom:15px;list-style-type:none;height:125px;">
            <div class="row col-md-12">
                <div class="col-md-2">
                <a href="{% url 'town.views.item_detail' pk=cart_item.item.pk %}"><img src="http://lorempixel.com/270/180/food/" width="125" height="125"></a></div>
                <div class="col-md-3">
                {{ cart_item.item.name|truncatechars:15 }}
                <br>
                <br>
                <br>
                <span class="text-danger">返品・交換対象外</span>
                </div>
                <div class="col-md-2" style="vertical-align:bottom;height:125px;">
                <span class="text-danger">¥</span><span class="text-danger">{{ cart_item.item.price|intcomma }}</span>
                </div>
                <div class="col-md-2">
                数量:<span>{{ cart_item.quantity }}</span>
                </div>
                <div class="col-md-2">
                <form action="{% url 'town.views.cart_delete' %}" method="POST" style="display:inline;">
                {% csrf_token %}
                <input type="hidden" name="item_id" value="{{ cart_item.item.pk }}" />
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-trash"></span> 削除</button>
                </form>
                </div>
            </div>
            </li>
    {% endfor %}
    </ul>
    {% endwith %}
{% endblock %}

town/templates/item/item_detail.html
{% extends 'town/base.html' %}
{% load humanize %}
{% block content %}
    <div class="row col-md-12">
            <div class="col-md-8">
                <img src="http://lorempixel.com/500/400/food/" alt="...">
                <br>
                <br>
                <br>
                <div>
                    <img src="http://lorempixel.com/35/42/food/" alt="...">
                    <img src="http://lorempixel.com/35/42/food/" alt="...">
                    <img src="http://lorempixel.com/35/42/food/" alt="...">
                    <img src="http://lorempixel.com/35/42/food/" alt="...">
                    <img src="http://lorempixel.com/35/42/food/" alt="...">
                </div>
            </div>
            <div class="col-md-4">
                <h3>{{ item.name }}</h3>
                <p class="text-danger" style="font-size:40px !important;">{{ item.price|intcomma }}</p>
                <div>
                    <img src="http://lorempixel.com/270/180/food/" alt="...">
                </div>
                <br>
                <div>
                    <form action="{% url 'town.views.cart_add' %}" method="POST" style="display:inline;">
                        {% csrf_token %}
                        <input type="hidden" name="item_id" value="{{ item.pk }}" />
                        <button type="submit" class="btn btn-warning {% if not user.is_authenticated %}disabled{% endif %}"><span class="glyphicon glyphicon-shopping-cart"></span> カートに入れる</button>
                    </form>
                    <button type="button" class="btn btn-default {% if not user.is_authenticated %}disabled{% endif %}"><span class="glyphicon glyphicon-heart" style="color:#d9534f !important;"></span></button>


                </div>
                
            </div>
            <div class="col-md-12">
                <h3>アイテム説明</h3>
                <div>
                {{ item.description|linebreaks }}
                </div>
            </div>
    </div>
{% endblock %}

town/templates/shop/shop_detail.html
{% extends 'town/base.html' %}
{% load humanize %} 
{% block content %}
    <h1>{{ shop.name }}</h1>
    <br>
    <br>
    {{ shop.description| linebreaks }}
    <h2>商品一覧</h2>
    
    {% with stocks=shop.stock_set.all %}
    {% if not stocks %}
    ただいま商品がありません。
    {% else %}
    <ul>
    {% for stock in stocks %}
        {% with item=stock.item %}
        <li><a href="{% url 'town.views.item_detail' pk=item.pk %}">{{ item.name }}　<br>
            金額　{{ item.price|intcomma }}
            <br>
            残り {{ stock.quantity }}
            <br>
        {% endwith %}
    {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    
{% endblock %}

town/templates/town/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DODOTOWN</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">DODOTOWN</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Link</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'town.views.cart_list' %}">お買い物かご</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
<style type="text/css">
.bs-docs-sidebar .nav>.active>a, .bs-docs-sidebar .nav>.active:hover>a, .bs-docs-sidebar .nav>.active:focus>a {
    padding-left: 18px;
    font-weight: 700;
    color: #563d7c;
    background-color: transparent;
    border-left: 2px solid #563d7c;
}
</style>
    <div class="row">
        <div class="col-md-2 col-xs-4">
            <nav class="bs-docs-sidebar">
                <ul class="nav bs-docs-sidenav">
                  <li role="presentation" class="active"><a href="/">Home</a></li>
                  <li role="presentation"><a href="#">HOGE</a></li>
                  <li role="presentation"><a href="#">Profile</a></li>
                  <li role="presentation"><a href="#">Messages</a></li>
                </ul>
            </nav>
        </div>
        <div class="col-md-9">
            {% if messages %}

                <div id="message_area" class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        {% for message in messages %}
                        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                        {% endfor %}
                </div>
<script>
$(function(){
    setTimeout(function(){
        $('#message_area').fadeOut();
    },5000);
});
</script>
            {% endif %}
            {% block content %}
            {% endblock %}
        </div>
    </div>
    
    
    
  </body>
</html>

town/templates/town/town_detail.html
{% extends 'town/base.html' %}
{% block content %}
    <h2>This is {{ town.name }}</h2>
    <ul>
    {% for shop in shops %}
        <li>
            <a href="{% url 'town.views.shop_detail' pk=shop.pk %}"><div>
                {{ shop.name }}
                <br />
                店長: {{ shop.owner }}
                <br />
                <br />
                店長の一言:
                {{ shop.description|linebreaks }}
                <br />
            </div></a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

town/templates/town/town_list.html
{% extends 'town/base.html' %}
{% block content %}
<ul>
{% for town in towns %}
    <li><a href="{% url 'town.views.town_detail' pk=town.pk %}">name: {{ town.name }}</a></li>
{% endfor %}
</ul>
{% endblock %}